# Generated by Django 5.0.2 on 2024-04-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentprofile'),
        ('api', '0007_student_activity_student_date_of_birth_and_more'),
    ]

    operations = [
    ]
