# Generated by Django 5.0.2 on 2024-04-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20240413_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passed_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='student',
            name='membership_in_organization',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.JSONField(default={}),
        ),
    ]
